### ISSUE TITLE
RAPSIM for manipulating APSIM simulation.How to do it ?

### ISSUE THREAD

**Issue by 13984489258** [APSIMInitiative/APSIMWheatPhenology#1]
Hi! I've been studying APSIM model for one year! But i don't know how to establish the relationship between R language and APSIM model. librarying the Rapsim package with R which is enough.how to prepare those simFiles, simFolders, simSuffix and osbfile ? where are the tutorials? and the code as follow is for Comparing simulated and measured values? Please take time out of your busy schedule to answer my questions. Have a nice day !!!
install.packages("devtools")
devtools::install_github("byzheng/rapsim")
force = TRUE
library(rapsim)

RApsim <- function( 
  para = NULL, 
  obsFile = NULL, 
  simFiles = NULL, 
  simFolders = NULL,
  simSuffix = "outputfile_daily",
  xvar = "DaysAfterSowing", ... )
{    
  para <- setpara( p = para, ... )
  
  # Create a new folder if the para$outputPrefix is a folder name
  if ( !is.null( para$outputPrefix ) && ( right( para$outputPrefix ) == "/" | right( para$outputPrefix ) == "\\" ) )
  {
    dir.create( para$outputPrefix, showWarnings = FALSE )
  }    
  
  # Read data
  sim <- readsim( simFiles, simFolders, simSuffix )
  obs <- readobs( obsFile )
  
  # Combine Data
  sim.obs <- combineObsSim( obs, sim, 
                            para$variables, 
                            para$identifiers,
                            para$isOutputObsData )
  
  # Plot the data
  all.plots <- NULL
  all.plots[[length( all.plots ) + 1]] <- 
    plotObsSimCompare( sim.obs, para$identifiers, para$variables )
  
  com.plots <- NULL
  if ( !is.null( sim.obs[[xvar]] ) & xvar %in% para$identifiers$sim )
  {
    xlab <- "Days After Sowing (d)"
    com.plots <- plotGraphCombinations( sim.obs, 
                                        graph.combinations = para$graph.combinations, 
                                        identifiers = para$identifiers,
                                        variables = para$variables,
                                        xvar = xvar,
                                        isOutputObsData = para$isOutputObsData )
    
    plots.num <- length( all.plots )
    for ( i in 1:length( com.plots ) )
    {
      plots.num <- plots.num + 1
      all.plots[[plots.num]] <- com.plots[[i]]
    }
  }
  
  filename <- NULL
  if ( para$outputPrefix == "" )
  {
    filename <- paste( "graph.simul-observed", ".", para$outputFormat, sep = "" )
  }
  else
  {
    filename <- paste( para$outputPrefix, ".", "graph.simul-observed", ".", para$outputFormat, sep = "" )
  }
  
  if ( para$outputFormat == "pdf" )
  {
    pdf( filename, paper = "a4", width = 8, height = 11, onefile = TRUE )
    for ( i in 1:length( all.plots ) )
    {
      print( all.plots[[i]] )
    }
    dev.off()
  }
  
}

**Comment by byzheng** [comment]
I think you used the old version of my package rapsim which I have dropped lots of functions. It would be better to ask question in the byzheng/rapsim. Not sure what you want to do.
