### ISSUE TITLE
ApsimX parameter estimation example

### ISSUE THREAD

**Issue by dxl-cde** [APSIMInitiative/APSIMWheatPhenology#2]
Hi Teacher Zheng

When I ran the apsimx example , I encountered the following problem（About the path）：

library(ApsimOnR)
library(CroptimizR)
library(dplyr)
library(nloptr)
library(DiceDesign)

# TEST ON ONE MODEL and ONE VARIABLE

start_time <- Sys.time()

# Select the model
simulation_name <- "GattonRowSpacingRowSpace25cm"

# define the variables list
variable_names=c("Wheat.Leaf.LAI")

# Getting apsimx file fro the package
apsimx_path="/usr/local/bin/Models"      **（In this here,I need to fill in the APSIM next generation installation path）**
**apsimx_path <- 'D:\\Program Files\\APSIMNG\\Bin\\Apsimx.exe'   This is my Apsim NG installation path,but it's wrong** 
**Error in system(cmd, wait = TRUE, intern = TRUE) : 'D:\Program' not found**
Thank you in advance

**Comment by byzheng** [comment]
I don't understand what you are doing here. This package is not related with apsimng. Are you working on rapsimng https://github.com/byzheng/rapsimng?

PS: your problem is related with space in the file path. Put into a file path without space or add double quotation round the file path.
